apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : my-app-dev
  namespace: argocd
  #finalizers:
  #- resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: argocd
  source:
    path   : "overlays/dev"
    repoURL: "https://github.com/777dimas/demo-app.git"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
      